import type { GitEngine } from '$engine/index';
import type { VirtualFileSystem } from '$engine/vfs';
import type { ShellResult } from './types';

// Auto-generated content templates for touch
const CONTENT_TEMPLATES = [
  'Hello, World!',
  'This is a placeholder file.',
  'TODO: add content here',
  'Lorem ipsum dolor sit amet.',
  'Sample text content.',
  'Auto-generated by gitverse.',
];

function autoContent(filename: string): string {
  // Deterministic based on filename length
  return CONTENT_TEMPLATES[filename.length % CONTENT_TEMPLATES.length];
}

/** Returns an error result if `path`'s parent dir is missing, else null. (Flat + 1-level VFS.) */
function missingDirError(
  vfs: VirtualFileSystem,
  path: string,
  cmd: string,
  verb: string,
): { output: string; exitCode: number } | null {
  const slashIdx = path.indexOf('/');
  if (slashIdx === -1) return null;
  const dir = path.substring(0, slashIdx);
  if (!vfs.exists(dir + '/')) {
    return { output: `${cmd}: cannot ${verb} '${path}': No such file or directory`, exitCode: 1 };
  }
  return null;
}

/**
 * Execute a shell builtin command against the engine's VFS.
 */
export function executeBuiltin(engine: GitEngine, command: string, args: string[]): ShellResult {
  const vfs = engine.getVFS();

  switch (command) {
    case 'ls': {
      const flags = new Set<string>();
      const paths: string[] = [];
      for (const arg of args) {
        if (arg.startsWith('-')) {
          for (const ch of arg.slice(1)) flags.add(ch);
        } else {
          paths.push(arg);
        }
      }
      const showAll = flags.has('a');
      const longFormat = flags.has('l');
      const dir = paths[0];

      let entries = vfs.listDir(dir);
      if (!showAll) {
        entries = entries.filter((e) => !e.startsWith('.'));
      }
      if (entries.length === 0) {
        return { output: '', exitCode: 0 };
      }
      if (longFormat) {
        const lines = entries.map((e) => {
          const perm = e.endsWith('/') ? 'drwxr-xr-x' : '-rw-r--r--';
          return `${perm}  ${e}`;
        });
        return { output: lines.join('\n'), exitCode: 0 };
      }
      return { output: entries.join('  '), exitCode: 0 };
    }

    case 'cat': {
      if (args.length === 0) {
        return { output: 'cat: missing operand', exitCode: 1 };
      }
      const path = args[0];
      if (!vfs.exists(path)) {
        return { output: `cat: ${path}: No such file or directory`, exitCode: 1 };
      }
      try {
        const content = vfs.readFile(path);
        return { output: content, exitCode: 0 };
      } catch {
        return { output: `cat: ${path}: Is a directory`, exitCode: 1 };
      }
    }

    case 'touch': {
      if (args.length === 0) {
        return { output: 'touch: missing operand', exitCode: 1 };
      }
      const path = args[0];
      if (vfs.exists(path)) {
        // Already exists — no-op (touch semantics: update mtime, but we just succeed)
        return { output: '', exitCode: 0 };
      }
      // Check if path includes a directory that doesn't exist
      const err = missingDirError(vfs, path, 'touch', 'touch');
      if (err) return err;
      const content = autoContent(path.split('/').pop() ?? path);
      vfs.createFile(path, content);
      return { output: '', exitCode: 0 };
    }

    case 'mkdir': {
      if (args.length === 0) {
        return { output: 'mkdir: missing operand', exitCode: 1 };
      }
      const raw = args[0];
      const name = raw.endsWith('/') ? raw.slice(0, -1) : raw;
      if (name.includes('/')) {
        return {
          output: `mkdir: cannot create directory '${raw}': only one level of nesting is supported`,
          exitCode: 1,
        };
      }
      if (vfs.exists(name + '/') || vfs.exists(name)) {
        return { output: `mkdir: cannot create directory '${raw}': File exists`, exitCode: 1 };
      }
      vfs.createDir(name);
      return { output: '', exitCode: 0 };
    }

    case 'echo': {
      let redirect: '>' | '>>' | null = null;
      let redirectIdx = -1;
      let gluedTarget = '';
      for (let i = 0; i < args.length; i++) {
        const a = args[i];
        if (a.startsWith('>>')) {
          redirect = '>>';
          redirectIdx = i;
          gluedTarget = a.slice(2);
          break;
        }
        if (a.startsWith('>')) {
          redirect = '>';
          redirectIdx = i;
          gluedTarget = a.slice(1);
          break;
        }
      }

      const contentTokens = redirect === null ? args : args.slice(0, redirectIdx);
      // Strip ALL double-quotes (not just one outer pair): the shell tokenizer
      // splits on whitespace before we see the input, so there is no quote-aware
      // tokenizer here — quotes only group words and are dropped.
      const content = contentTokens.join(' ').replace(/"/g, '');

      if (redirect === null) {
        return { output: content, exitCode: 0 };
      }

      const target = gluedTarget || args[redirectIdx + 1];
      if (!target) {
        return { output: 'echo: missing redirect target', exitCode: 1 };
      }

      const dirErr = missingDirError(vfs, target, 'echo', 'create');
      if (dirErr) return dirErr;

      if (redirect === '>') {
        vfs.createFile(target, content);
      } else {
        const existing = vfs.exists(target) ? vfs.readFile(target) : '';
        vfs.createFile(target, existing === '' ? content : existing + '\n' + content);
      }
      return { output: '', exitCode: 0 };
    }

    case 'rm': {
      if (args.length === 0) {
        return { output: 'rm: missing operand', exitCode: 1 };
      }
      const path = args[0];
      if (path === '.git' || path === '.git/') {
        return { output: 'rm: cannot remove .git: protected directory', exitCode: 1 };
      }
      if (!vfs.exists(path)) {
        return { output: `rm: cannot remove '${path}': No such file or directory`, exitCode: 1 };
      }
      try {
        vfs.deleteFile(path);
        return { output: '', exitCode: 0 };
      } catch (err) {
        const msg = err instanceof Error ? err.message : String(err);
        return { output: `rm: ${msg}`, exitCode: 1 };
      }
    }

    case 'mv': {
      if (args.length < 2) {
        return { output: 'mv: missing destination operand', exitCode: 1 };
      }
      const [src, dst] = args;
      if (!vfs.exists(src)) {
        return {
          output: `mv: cannot stat '${src}': No such file or directory`,
          exitCode: 1,
        };
      }
      try {
        vfs.moveFile(src, dst);
        return { output: '', exitCode: 0 };
      } catch (err) {
        const msg = err instanceof Error ? err.message : String(err);
        return { output: `mv: ${msg}`, exitCode: 1 };
      }
    }

    case 'clear': {
      // Special escape marker that the terminal UI can detect
      return { output: '\x1b[CLEAR]', exitCode: 0 };
    }

    case 'help': {
      const lines = [
        'Available commands:',
        '',
        '  Git commands:',
        '    git add <file|.>',
        '    git commit -m "<message>"',
        '    git status',
        '    git log',
        '    git diff [file]',
        '    git branch [name]',
        '    git checkout <branch|commit>',
        '    git switch <branch>',
        '    git merge <branch>',
        '    git rebase <branch>',
        '    git reset [--soft|--mixed|--hard] <ref>',
        '    git stash [pop|apply|list|drop]',
        '    git tag [name]',
        '    git rm <file>',
        '    git mv <src> <dst>',
        '    git cherry-pick <hash>',
        '    git revert <hash>',
        '',
        '  File builtins:',
        '    ls [dir]          — list files',
        '    cat <file>        — show file content',
        '    touch <file>      — create file (hint: use this to add files!)',
        '    mkdir <dir>       — create a folder (one level max)',
        '    echo <text> > <file>   — write text to a file (overwrite)',
        '    echo <text> >> <file>  — append text (use to modify tracked files!)',
        '    rm <file>         — delete file',
        '    mv <src> <dst>    — move/rename file',
        '    clear             — clear the terminal',
        '',
        '  Other:',
        '    help              — show this message',
      ];
      return { output: lines.join('\n'), exitCode: 0 };
    }

    default:
      return { output: `${command}: command not found`, exitCode: 127 };
  }
}
