import type { GitEngine } from '$engine/index';
import type { ShellResult } from './types';

// Auto-generated content templates for touch
const CONTENT_TEMPLATES = [
  'Hello, World!',
  'This is a placeholder file.',
  'TODO: add content here',
  'Lorem ipsum dolor sit amet.',
  'Sample text content.',
  'Auto-generated by gitverse.',
];

function autoContent(filename: string): string {
  // Deterministic based on filename length
  return CONTENT_TEMPLATES[filename.length % CONTENT_TEMPLATES.length];
}

/**
 * Execute a shell builtin command against the engine's VFS.
 */
export function executeBuiltin(engine: GitEngine, command: string, args: string[]): ShellResult {
  const vfs = engine.getVFS();

  switch (command) {
    case 'ls': {
      const flags = new Set<string>();
      const paths: string[] = [];
      for (const arg of args) {
        if (arg.startsWith('-')) {
          for (const ch of arg.slice(1)) flags.add(ch);
        } else {
          paths.push(arg);
        }
      }
      const showAll = flags.has('a');
      const longFormat = flags.has('l');
      const dir = paths[0];

      let entries = vfs.listDir(dir);
      if (!showAll) {
        entries = entries.filter((e) => !e.startsWith('.'));
      }
      if (entries.length === 0) {
        return { output: '', exitCode: 0 };
      }
      if (longFormat) {
        const lines = entries.map((e) => {
          const perm = e.endsWith('/') ? 'drwxr-xr-x' : '-rw-r--r--';
          return `${perm}  ${e}`;
        });
        return { output: lines.join('\n'), exitCode: 0 };
      }
      return { output: entries.join('  '), exitCode: 0 };
    }

    case 'cat': {
      if (args.length === 0) {
        return { output: 'cat: missing operand', exitCode: 1 };
      }
      const path = args[0];
      if (!vfs.exists(path)) {
        return { output: `cat: ${path}: No such file or directory`, exitCode: 1 };
      }
      try {
        const content = vfs.readFile(path);
        return { output: content, exitCode: 0 };
      } catch {
        return { output: `cat: ${path}: Is a directory`, exitCode: 1 };
      }
    }

    case 'touch': {
      if (args.length === 0) {
        return { output: 'touch: missing operand', exitCode: 1 };
      }
      const path = args[0];
      if (vfs.exists(path)) {
        // Already exists — no-op (touch semantics: update mtime, but we just succeed)
        return { output: '', exitCode: 0 };
      }
      // Check if path includes a directory that doesn't exist
      const slashIdx = path.indexOf('/');
      if (slashIdx !== -1) {
        const dir = path.substring(0, slashIdx);
        if (!vfs.exists(dir + '/')) {
          return {
            output: `touch: cannot touch '${path}': No such file or directory`,
            exitCode: 1,
          };
        }
      }
      const content = autoContent(path.split('/').pop() ?? path);
      vfs.createFile(path, content);
      return { output: '', exitCode: 0 };
    }

    case 'rm': {
      if (args.length === 0) {
        return { output: 'rm: missing operand', exitCode: 1 };
      }
      const path = args[0];
      if (path === '.git' || path === '.git/') {
        return { output: 'rm: cannot remove .git: protected directory', exitCode: 1 };
      }
      if (!vfs.exists(path)) {
        return { output: `rm: cannot remove '${path}': No such file or directory`, exitCode: 1 };
      }
      try {
        vfs.deleteFile(path);
        return { output: '', exitCode: 0 };
      } catch (err) {
        const msg = err instanceof Error ? err.message : String(err);
        return { output: `rm: ${msg}`, exitCode: 1 };
      }
    }

    case 'mv': {
      if (args.length < 2) {
        return { output: 'mv: missing destination operand', exitCode: 1 };
      }
      const [src, dst] = args;
      if (!vfs.exists(src)) {
        return {
          output: `mv: cannot stat '${src}': No such file or directory`,
          exitCode: 1,
        };
      }
      try {
        vfs.moveFile(src, dst);
        return { output: '', exitCode: 0 };
      } catch (err) {
        const msg = err instanceof Error ? err.message : String(err);
        return { output: `mv: ${msg}`, exitCode: 1 };
      }
    }

    case 'clear': {
      // Special escape marker that the terminal UI can detect
      return { output: '\x1b[CLEAR]', exitCode: 0 };
    }

    case 'help': {
      const lines = [
        'Available commands:',
        '',
        '  Git commands:',
        '    git add <file|.>',
        '    git commit -m "<message>"',
        '    git status',
        '    git log',
        '    git diff [file]',
        '    git branch [name]',
        '    git checkout <branch|commit>',
        '    git switch <branch>',
        '    git merge <branch>',
        '    git rebase <branch>',
        '    git reset [--soft|--mixed|--hard] <ref>',
        '    git stash [pop|apply|list|drop]',
        '    git tag [name]',
        '    git rm <file>',
        '    git mv <src> <dst>',
        '    git cherry-pick <hash>',
        '    git revert <hash>',
        '',
        '  File builtins:',
        '    ls [dir]          — list files',
        '    cat <file>        — show file content',
        '    touch <file>      — create file (hint: use this to add files!)',
        '    rm <file>         — delete file',
        '    mv <src> <dst>    — move/rename file',
        '    clear             — clear the terminal',
        '',
        '  Other:',
        '    help              — show this message',
      ];
      return { output: lines.join('\n'), exitCode: 0 };
    }

    default:
      return { output: `${command}: command not found`, exitCode: 127 };
  }
}
